# --- Change what appears in the banner and meta data of your pages --- #
title: Martin's Demonstration Site
description: This is illustrates how to use the template.

# --- Specify the language of site --- #
lang: en

plugins:
  - jekyll-feed
  - jekyll-seo-tag

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/figure

# --- List of pages in your site --- #
# --- Only change these if you change the name of your .md files --- #
# --- And, only change the names of the HTML files named after each colon: e.g. page2.html --- #
github:
  page1: index.html
  page2: page2.html
  page3: page3.html
  page4: page4.html
  page5: page5.html
  page6: audio.html
  page7: song.html
  page8: video.html
  
# --- List of links in the navigation bar --- #
# --- Change the words after the colons to change your navigation labels --- #
navbar-links:
  page1: Home
  page2: Birds
  page3: 3 Column Layout
  page4: Portugal
  page5: H5P with Audio
  page6: Audio Examples
  Page7: Song
  Page8: video Examples
